package com.dwws.imo.dao.jpa;

public enum IMONamedQuery {
	BUSCA_EMPREGADOR_POR_USUARIO_SENHA,
	BUSCA_EMPREGADOR_POR_CNPJ,
	BUSCA_EMPREGADOR_POR_USUARIO,
	BUSCA_TRABALHADOR_POR_USUARIO_SENHA,
	BUSCA_TRABALHADOR_POR_USUARIO,
	BUSCA_TRABALHADOR_POR_CPF,
	BUSCA_CANDIDATURA_POR_IDTRABALHADOR_CODIGOVAGA,
	CONTAGEM_VAGAS_DISPONIVEIS;
}
